# Generated by Django 2.2.1 on 2020-11-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201115_0953'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table=None,
        ),
        migrations.AlterModelTable(
            name='volunteer',
            table=None,
        ),
    ]
