# Generated by Django 2.2.1 on 2020-11-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201115_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='date_joined',
        ),
    ]
